FROM magento/magento-cloud-docker-php:8.1-fpm-1.3.2

WORKDIR /app

ARG COMPOSER_VERSION=2.1.14
ARG COMPOSER_ALLOW_SUPERUSER=1
ARG COMPOSER_HOME=/composer
ARG CRONTAB=""

ENV COMPOSER_MEMORY_LIMIT -1
ENV COMPOSER_ALLOW_SUPERUSER ${COMPOSER_ALLOW_SUPERUSER}
ENV COMPOSER_HOME ${COMPOSER_HOME}
ENV PHP_MEMORY_LIMIT -1


# Configure Node.js version
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash


# Install dependencies
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
  cron \
  git \
  mariadb-client \
  nano \
  nodejs \
  python3 \
  python3-pip \
  redis-tools \
  unzip \
  vim \
  openssh-client \
  lsof


# Install PyYAML
RUN pip3 install --upgrade setuptools \
    && pip3 install pyyaml

# Install Grunt
RUN npm install -g grunt-cli


COPY .docker/php/etc/php-cli.ini /usr/local/etc/php/conf.d/zz-magento.ini
COPY .docker/php/etc/php-xdebug.ini /usr/local/etc/php/conf.d/zz-xdebug-settings.ini
COPY .docker/php/etc/php-pcov.ini /usr/local/etc/php/conf.d/zz-pcov-settings.ini
COPY .docker/php/etc/mail.ini /usr/local/etc/php/conf.d/zz-mail.ini
COPY .docker/php/etc/php-gnupg.ini /usr/local/etc/php/conf.d/gnupg.ini

# Get composer installed to /usr/local/bin/composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --version=${COMPOSER_VERSION} --filename=composer

COPY .docker/php/bin/* /usr/local/bin/

RUN ["chmod", "+x", \
    "/usr/local/bin/magento-installer", \
    "/usr/local/bin/magento-command", \
    "/usr/local/bin/mftf-command", \
    "/usr/local/bin/ece-command", \
    "/usr/local/bin/cloud-build", \
    "/usr/local/bin/cloud-deploy", \
    "/usr/local/bin/cloud-post-deploy", \
    "/usr/local/bin/run-cron", \
    "/usr/local/bin/run-hooks" \
]

RUN chown -R www:www /etc/cron.d ${MAGENTO_ROOT} ${COMPOSER_HOME}

RUN if [ ! -z "${CRONTAB}" ]; then echo "${CRONTAB}" > /etc/cron.d/magento && touch /var/log/cron.log ; fi

COPY . .

COPY .docker/php/readiness-probe.sh /readiness-probe.sh
RUN chmod +x /readiness-probe.sh

COPY .docker/php/development-entrypoint.sh /development-entrypoint.sh
RUN chmod +x /development-entrypoint.sh

ENTRYPOINT ["/development-entrypoint.sh"]
CMD ["php-fpm", "-R"]
