apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/component: backend-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend-api
    spec:
      containers:
        - name: backend
          image: {{ .Values.serviceImage }}
          ports:
            - containerPort: 3080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.host }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: FRONTEND_URL
              value: {{ .Values.frontendUrl }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  revisionHistoryLimit: 10

